spring:
  application:
    name: HelloWorld

tracks:
  track1:
    id: 1
    courses:
      - math
      - chemistry
      - physics
  track2:
    id: 2
    courses:
      - art
      - literature
      - music

server:
  application:
    name: InjectMapFromYAML
    url: https://injectmapfromyaml.dev
    description: How To Inject a map from a YAML File in Spring Boot
  config:
    ips:
      - 10.10.10.10
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13
    filesystem:
      - /dev/root
      - /dev/md2
      - /dev/md4
  users:
    root:
      username: root
      password: rootpass
    guest:
      username: guest
      password: guestpass